In [2]:
import torch
from torch.nn.utils.rnn import pad_sequence

# 1. 将每一行分别包装成 torch.tensor，形成一个列表
a = [
    torch.tensor([(2, 3), (4, 5), (6, 7)]), 
    torch.tensor([(2, 3), (4, 5)]), 
    torch.tensor([(2, 3)])
]

# 2. 使用 pad_sequence 进行自动补齐
# padding_value=0 是默认值，你可以根据需要更改
b = pad_sequence(a, batch_first=True, padding_value=0)

print(b)
print("Shape:", b.shape)

tensor([[[2, 3],
         [4, 5],
         [6, 7]],

        [[2, 3],
         [4, 5],
         [0, 0]],

        [[2, 3],
         [0, 0],
         [0, 0]]])
Shape: torch.Size([3, 3, 2])


In [11]:
# dim=-1 表示拆解最后一维
c = b[..., 0]
d = b[..., 1]

print(c.shape) # 结果是 (3, 3)
print(d.shape) # 结果是 (3, 3)
print(c)
print(d)

torch.Size([3, 3])
torch.Size([3, 3])
tensor([[2, 4, 6],
        [2, 4, 0],
        [2, 0, 0]])
tensor([[3, 5, 7],
        [3, 5, 0],
        [3, 0, 0]])


In [12]:
a = [0, 0, 0, 0]
print(a[2:10])

[0, 0]


In [10]:
import torch
data = torch.load("processed_data/sliced_trials.pt")

C:\Users\17927\AppData\Local\Temp\ipykernel_37952\1975263015.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data = torch.load("processed_data/sliced_trials.pt")


In [15]:
for trial in range(len(data)):
    for bin in range(len(data[trial]["spikes"])):
        if data[trial]["spikes"][bin] == 0:
            print(trial, bin)

45 76
106 52
109 69
155 59
158 60
160 58
174 63
190 62
245 67
284 49
301 52
310 68
317 46
333 67
338 54
343 49
358 65
407 60
413 57
424 53
441 56
446 71
457 64
517 68
533 57
603 55
627 57
642 58
663 59
753 47
780 59
781 57
822 55
844 61
938 59
1029 59
1035 53
1065 48
1067 61
1073 62
1076 61
1083 67
1125 58
1134 69
1144 58
1145 59
1201 65
1262 51
1297 70
1299 80
1376 43
1401 63
1427 51
1431 56
1446 60
1450 49
1459 47
1465 63
1473 53
1474 56
1487 66
1493 57
1495 49
1502 65
1531 62
1552 53
1594 61
1605 48
1611 45
1645 66
1647 52
1654 57
1675 59
1714 62
1721 57
1757 43
1771 59
1851 59
1853 57
1867 62
1887 56
1888 56
1908 51
1911 69
1938 57
1975 53
2003 62
2010 53
2057 59
2064 61
2111 58
2118 69
2125 57
2129 66
2133 73
2145 61
2155 55
2180 53
2220 59
2241 61
2247 53


In [18]:
data[45]["spikes"][76]

0

In [20]:
print(torch.zeros((0, 2)))

tensor([], size=(0, 2))


In [7]:
from Dataloader import WindowedDataset
dataset = WindowedDataset("processed_data/sliced_trials.pt")

In [2]:
dataset[0][0][2].shape


torch.Size([43, 2])

In [20]:
num = 0
for i in range(len(dataset)):
    if dataset[i][1].shape[0] <= 2:
        num += 1
        print("i", i)
        print(dataset[i][1].shape)
print(num)

i 351
torch.Size([2, 2])
i 886
torch.Size([2, 2])
i 1012
torch.Size([2, 2])
i 2049
torch.Size([2, 2])
i 2344
torch.Size([2, 2])
i 2708
torch.Size([2, 2])
i 3374
torch.Size([2, 2])
i 3906
torch.Size([2, 2])
i 4370
torch.Size([2, 2])
i 4472
torch.Size([2, 2])
i 4645
torch.Size([2, 2])
i 4939
torch.Size([2, 2])
i 5344
torch.Size([2, 2])
i 5536
torch.Size([2, 2])
i 6210
torch.Size([2, 2])
i 6388
torch.Size([2, 2])
i 6459
torch.Size([2, 2])
i 7085
torch.Size([2, 2])
i 7548
torch.Size([2, 2])
i 8525
torch.Size([2, 2])
i 8587
torch.Size([2, 2])
i 8890
torch.Size([2, 2])
i 9057
torch.Size([2, 2])
i 9232
torch.Size([2, 2])
i 9334
torch.Size([2, 2])
i 10102
torch.Size([2, 2])
i 10164
torch.Size([2, 2])
i 10563
torch.Size([2, 2])
i 10836
torch.Size([2, 2])
i 11010
torch.Size([2, 2])
i 11205
torch.Size([2, 2])
i 11331
torch.Size([2, 2])
i 11381
torch.Size([2, 2])
i 11796
torch.Size([2, 2])
i 12298
torch.Size([2, 2])
i 13450
torch.Size([2, 2])
i 14234
torch.Size([2, 2])
i 14798
torch.Size([2, 2])
i

In [17]:
print(data[0]["vel"].shape[0] // 50)
print(data[0]["vel"].shape[0] % 50)

64
42


In [21]:
a = torch.tensor([0, 1, 2, 3, 4, 5])
print(a.view(2, 3))

tensor([[0, 1, 2],
        [3, 4, 5]])
